### ISSUE TITLE
Remove google analytics

### ISSUE THREAD

**Issue by King-Mob** [WeCollective/webapp#10]

**Comment by lmenus** [comment]
Why are we removing GA @King-Mob?

**Comment by King-Mob** [comment]
@lmenus James and Leo asked to switch from GA to Matomo, they don't want Big Data to have their data

**Comment by lmenus** [comment]
@King-Mob I have rebuilt `package-lock.json`, I guess you didn't remove `angular-google-analytics` using the `npm remove` command? Should be completely removed from the project now.
