### ISSUE TITLE
“Error posting comment.”

### ISSUE THREAD

**Issue by King-Mob** [WeCollective/webapp#14]
error every time a new comment is created (comment is still successfully posted)

**Comment by lmenus** [comment]
[Fixed](https://github.com/WeCollective/server/blob/96c101ce8e97111ba522ca8bd0062d435568767b/routers/post/controller.js#L1304-L1444).

**Comment by jhweir** [comment]
Since this bug was resolved, the number of comments each post has (visible below the posts title when displayed on walls and above comment threads) is no longer updating. See: https://www.weco.io/b/root/p/dave-1550755041204 for an example.

**Comment by lmenus** [comment]
I’ll investigate what’s going wrong, can’t see anything based on the referenced commit, will need to run the code
