### ISSUE TITLE
“Branch does not exist.”

### ISSUE THREAD

**Issue by King-Mob** [WeCollective/webapp#17]
error appears when upvoting any post that has been tagged with a branch that has since been deleted. examples include: 
https://www.weco.io/b/nature/p/harold-1518738104939 https://www.weco.io/b/technology/p/leosammallahti-1529837960810 https://www.weco.io/b/technology/p/mrbombastic-1530042450076
The effect of the upvote (or removing an upvote if the user has already voted on it) is applied to the post but doesn’t appear to the user, so they can upvote (or remove their upvote) an unlimited number of times, thus adding (or removing) as many points as they want from those posts.

**Comment by lmenus** [comment]
@King-Mob Are you able to document steps to reproduce this issue please?

**Comment by lmenus** [comment]
cc @jhweir

**Comment by lmenus** [comment]
There might be more bugs related to actions on a post that existed in a previously deleted branch. Has anyone looked into comments, etc?
