### ISSUE TITLE
Some URLs aren't allowed

### ISSUE THREAD

**Issue by King-Mob** [WeCollective/webapp#18]
Some url’s (such as: https://www.mitpressjournals.org/doi/abs/10.1162/NECO_a_00475) aren’t allowed when added to the ‘create new post’ modal and are being changed (in the case of the above url, simplified to: https://www.mitpressjournals.org/). This appears to have occurred since the recent update that crawls url links to auto-generate titles and descriptions for posts, but so far I have only noticed it on the above address.

**Comment by lmenus** [comment]
Moving [here](https://github.com/WeCollective/server/issues/3)
